import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";


import styles from "styles/app.module.scss";

interface IProps {
  hello: string;
}

const Home: NextPage<IProps> = ({ hello }): JSX.Element => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <Image src="/test.jpg" layout="fill" alt="test" />
    </main>
  </div>
);

export const getServerSideProps = async (ctx) => ({
  props: {
    hello: "Server Side Props",
  },
});

export default Home;
