import { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";

import Hello from "components/Hello";

import styles from "styles/app.module.scss";

interface IProps {
  hello: string;
}

const Home: NextPage<IProps> = ({ hello }): JSX.Element => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <Hello />
      <p>{hello}</p>

      <hr />

      <Link href="/original">
        <a>The Original Starter Page (Client side link)</a>
      </Link>
    </main>
  </div>
);

export const getServerSideProps = async (ctx) => ({
  props: {
    hello: "Server Side Props",
  },
});

export default Home;
