import { GetServerSideProps, NextPage } from "next";
import Link from "next/link";
import Head from "next/head";

import Pagination from "components/Pagination";

import styles from "styles/app.module.scss";

export interface Item {
  title: string;
  desc: string;
}

export interface IProps {
  hello: string;
  file: Item[];
}
const Home: NextPage<IProps> = ({ file }): JSX.Element => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      {console.log(file)}
      <Pagination data={file} />
    </main>
  </div>
);

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const file = await fetch("http://localhost:3000/files/test.json");
  const fileJsonResponse = await file.json();

  return {
    props: {
      hello: "Server Side Props",
      file: fileJsonResponse,
    },
  };
};

export default Home;
